services:
  - type: web
    name: btech-buddy-backend
    env: node
    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 18.x
      # Required environment variables (set these in Render dashboard):
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "*"  # Update this to your frontend URL in production
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: |
      echo "Starting build process..."
      npm install -g npm@latest
      npm install -g n
      n 18.20.2
      node -v
      npm -v
      
      # Install dependencies
      npm install
      
      # Build the frontend
      npm run build
      
      # Install backend dependencies
      cd backend
      npm install --production
      cd ..
      
      echo "Build completed successfully!"
