services:
  - type: web
    name: btech-buddy-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Add these environment variables in Render dashboard:
      # - MONGODB_URI: Your MongoDB Atlas connection string
      # - JWT_SECRET: Your JWT secret key
      # - Any other required environment variables
    plan: free
    region: oregon
    autoDeploy: true
